
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[355] =
    {   0,
        0,    0,    0,    0,    0,    0,   10,   10,   68,   66,
       60,   62,   61,   62,   33,    8,   63,   31,   66,   27,
       37,   19,   35,   20,   30,   66,   21,   64,   64,   39,
       29,   18,   24,   63,   63,   28,   38,   43,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   25,   66,   36,    3,    2,
        2,    7,    6,    6,    7,   10,    9,    9,   14,   12,
       62,   32,   63,   63,   17,   59,   40,   65,    0,    0,
        4,    1,   65,    0,    0,    0,   64,   64,    0,   41,
       26,   22,   23,   42,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,   63,   59,
       63,   63,   63,   63,   63,   63,   63,   63,   49,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   34,
        2,    6,    5,   10,    0,    9,   13,   11,   11,   10,
        0,   65,    0,    0,   65,    0,   64,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   59,   63,   63,   63,   50,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,    0,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   48,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   16,   63,   57,
       63,   63,    0,   63,   63,   63,   63,   63,   63,   45,
       63,   63,   63,   63,   15,   59,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       59,   63,   63,   63,   58,    0,   63,   56,   59,   63,
       63,   63,   63,   47,   63,   63,   63,   63,   63,   63,

       63,   63,   53,   54,   55,   63,   63,   63,   63,   63,
       46,   59,    0,   63,   44,   63,   63,   63,   63,   63,
       63,   63,   63,   63,    0,    0,   63,   63,   63,   63,
       63,   63,    0,    0,   63,   63,   63,    0,    0,   63,
        0,    0,   63,    0,    0,    0,    0,    0,    0,    0,
        0,   52,   51,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    2,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[362] =
    {   0,
        0,    0,   60,   61,   64,   65,   68,   69,  301, 1111,
     1111, 1111, 1111,  293,  267, 1111,   60, 1111,  277, 1111,
     1111, 1111,  268, 1111,   58,   64,   68,   68,   85, 1111,
       67,  257,   68,   88,   76, 1111, 1111, 1111,   93,   95,
       97,  117,  100,  105,  121,  112,  137,  123,  148,  153,
      155,  158,  171,  160,  176, 1111,  214, 1111, 1111, 1111,
      270, 1111, 1111,  262,  241,  227, 1111,  249, 1111,  198,
     1111, 1111,  102,    0, 1111, 1111, 1111,  200,  203,  211,
     1111, 1111,  220,  235,  211,  223,  243,  258,  246, 1111,
     1111, 1111, 1111, 1111,  215,  251,  178,  266,  269,  274,

      278,  286,  169,  288,  290,  292,  294,  296,  298,  300,
      303,  311,  313,  316,  319,  325,  327,  329,  331,  336,
      338,  340,  343,  348,  351,  355,  359,  363,  373,  380,
      385,  389,  391,  393,  395,  397,  401,  404,  410, 1111,
     1111, 1111, 1111,  217,  425, 1111, 1111, 1111,  239,  202,
      177,  440,  423,  428,  438,  443,  448,  450,  460,  463,
      470,  478,  480,  465,  485,  487,  407,  490,  499,  502,
      505,  507,  510,  514,  516,  521,  523,  525,  527,  530,
      533,  537,  546,  551,  553,  555,  557,  560,  562,  564,
      566,  569,  571,  581,  590,  584,  593,  595,  598,  603,

      605,  607,  610,  622,  612,  624,  618,  626,  178,  628,
      639,  643,  645,  647,  650,  653,  655,  657,  663,  665,
      668,  670,  672,  676,  678,  686,  688,  690,  694,  698,
      703,  708,  710,  712,  718,  720,  724,  728,  730,  736,
      739,  748,  744,  753,  755,  757,  759,  763,  766,  771,
      773,  778,  164,  780,  782,  784,  786,  788,  804,  807,
      809,  812,  814,  816,  822,  824,  826,  828,  830,  835,
      840,  842,  844,  847,  851,  856,  865,  869,  871,  873,
      875,  878,  880,  885,  887,  173,  889,  891,  896,  898,
      905,  909,  911,  916,  918,  921,  923,  928,  925,  930,

      934,  936,  938,  946,  951,  954,  956,  960,  962,  964,
     1111,  970,  161,  966,  972,  976,  980,  982,  986,  988,
      991,  996, 1004, 1009,  155,  139, 1011, 1013, 1015, 1017,
     1022, 1019,  151,  129, 1025, 1029, 1036,  120,  147, 1039,
      108,  104, 1046,  111,   94,  112,   92,   82,   80,   58,
       51, 1111, 1111, 1111, 1095, 1098, 1101,   98, 1104, 1107,
       91
    } ;

static const flex_int16_t yy_def[362] =
    {   0,
      354,    1,  355,  355,  356,  356,  357,  357,  354,  354,
      354,  354,  354,  354,  354,  354,  358,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  358,  358,  354,  354,  354,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  359,  354,  354,  354,  360,
      354,  354,  358,  361,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  358,  358,  358,  361,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  354,
      354,  354,  354,  359,  354,  354,  354,  354,  354,  359,
      354,  354,  354,  354,  354,  354,  354,  358,  358,  358,
      361,  361,  361,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  354,  358,
      358,  358,  361,  361,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  354,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  354,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      354,  358,  354,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  354,  354,  358,  358,  358,  358,
      358,  358,  354,  354,  358,  358,  358,  354,  354,  358,
      354,  354,  358,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,    0,  354,  354,  354,  354,  354,  354,
      354
    } ;

static const flex_int16_t yy_nxt[1174] =
    {   0,
       10,   11,   12,   13,   14,   11,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   17,   17,   34,   35,   36,
       10,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   17,   47,   17,   17,   48,   17,   49,   17,   50,
       51,   52,   53,   17,   54,   55,   17,   17,   17,   56,
       57,   58,   60,   60,   61,   61,   63,   63,   64,   64,
       67,   67,   68,   68,   76,   69,   69,   65,   65,   74,
       74,   81,   77,   78,   78,   83,   82,   84,   84,   90,
       91,   93,   94,   74,   85,   74,   74,   79,   70,   70,

       73,   86,   83,  353,   87,   88,   85,   74,   74,   80,
      352,   85,   98,   98,   74,   74,   74,   74,   89,   74,
       74,   74,   74,   85,   74,   74,   99,  351,   96,  350,
      100,   74,   74,   97,  349,   95,   74,   74,  109,  348,
       74,   74,   74,   74,  347,  102,  101,  103,  110,  346,
      111,  105,  112,  345,  104,  114,   74,   74,  106,  344,
      118,  113,  107,  115,  342,  108,  116,   74,   74,  117,
      341,  122,   74,   74,   74,   74,  119,   74,   74,   74,
       74,  339,  123,  120,  121,  338,  124,  126,   74,   74,
       74,   74,  334,  129,  137,   74,   74,   74,   74,  130,

      148,  125,  149,  127,  333,  150,  128,  167,  138,  326,
      131,  132,  135,  133,  311,  134,  286,  139,  253,   78,
       78,  136,   78,   78,  209,  154,   85,  154,  150,  160,
      155,  155,  145,   79,   74,   74,   79,  150,   85,  152,
      152,  148,   84,   84,  156,  150,   85,  145,  150,  151,
      150,  146,   83,  153,   84,   84,   86,  145,   85,  143,
       83,   85,   87,   87,  142,  157,  157,  158,   86,   85,
       74,   74,  141,   85,  140,   83,   89,   87,   88,   89,
       92,   85,   76,   83,   85,  161,  161,   75,   98,   98,
       72,   89,  162,   74,   74,   71,   85,   74,   74,  163,

      354,  159,   99,  354,  162,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,  354,   74,   74,  354,  164,  171,  354,  172,  165,
       74,   74,   74,   74,  166,   74,   74,  174,   74,   74,
      168,  169,  170,  173,   74,   74,   74,   74,   74,   74,
       74,   74,  354,  175,  176,   74,   74,   74,   74,   74,
       74,  179,   74,   74,  177,  178,  180,   74,   74,  354,
       74,   74,  354,  181,   74,   74,  354,  182,   74,   74,
      354,  183,   74,   74,  354,  184,  354,  187,  354,  185,
      186,  190,   74,   74,  354,  188,  189,  354,  193,   74,

       74,  191,  354,  182,   74,   74,  354,  192,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,  354,  196,
       74,   74,  354,   74,   74,  194,   74,   74,  195,   74,
       74,  203,  144,  199,  354,  197,  354,  201,  198,  354,
      200,  218,  152,  152,  354,  202,  206,  155,  155,  207,
      204,  205,  208,  354,  182,  144,  153,  155,  155,  152,
      152,  156,  155,  155,  144,   83,   85,   87,   87,   74,
       74,  156,  144,  153,   85,  144,  156,  144,   85,   74,
       74,   89,   74,   74,   74,   74,   85,   83,  210,  161,
      161,  354,  154,  354,  154,  354,  162,  213,  213,  161,

      161,  354,  211,  163,   74,   74,   74,   74,  162,   74,
       74,  214,  354,  163,  354,  212,  354,  215,   74,   74,
      354,   74,   74,  216,   74,   74,   74,   74,  182,   74,
       74,  354,  217,   74,   74,   74,   74,  182,  219,  354,
       74,   74,   74,   74,   74,   74,   74,   74,  223,   74,
       74,  224,   74,   74,  354,  182,   74,   74,  220,  225,
      354,  221,  222,  226,  228,   74,   74,  229,  354,  182,
       74,   74,   74,   74,   74,   74,   74,   74,  227,   74,
       74,   74,   74,   74,   74,   74,   74,  354,   74,   74,
       74,   74,  354,  233,  182,  354,  230,  182,  354,  231,

       74,   74,  234,   74,   74,  232,  354,  182,  235,   74,
       74,  354,   74,   74,   74,   74,  238,   74,   74,  354,
      236,  237,   74,   74,   74,   74,   74,   74,  354,   74,
       74,   74,   74,  243,  239,  242,  241,   74,   74,  245,
      240,   74,   74,   74,   74,   74,   74,   74,   74,  354,
      244,  354,  251,  354,  249,  246,  182,  247,   74,   74,
      248,  250,   74,   74,  213,  213,  213,  213,  254,   74,
       74,  252,   74,   74,   74,   74,   74,   74,  214,  354,
      214,  256,   74,   74,   74,   74,  255,   74,   74,   74,
       74,   74,   74,  259,  354,   74,   74,   74,   74,  354,

      257,  182,  354,  258,  182,   74,   74,   74,   74,   74,
       74,  354,  261,   74,   74,  354,  260,   74,   74,  354,
      182,  263,   74,   74,  354,  262,  265,   74,   74,   74,
       74,   74,   74,  264,  354,  266,  267,   74,   74,   74,
       74,  354,  269,   74,   74,  354,  182,   74,   74,   74,
       74,  354,  272,  268,  273,   74,   74,  354,   74,   74,
      270,  354,  274,   74,   74,  354,  271,   74,   74,  354,
      275,  354,   74,   74,   74,   74,   74,   74,   74,   74,
      276,  277,   74,   74,  278,   74,   74,  354,  182,  279,
       74,   74,   74,   74,  182,  354,  280,   74,   74,   74,

       74,   74,   74,   74,   74,   74,   74,   74,   74,  354,
      282,  354,  281,  354,  283,  354,  285,  354,  287,  354,
      290,  354,  288,   74,   74,  284,   74,   74,   74,   74,
      289,   74,   74,   74,   74,   74,   74,  354,  291,  354,
      182,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,  354,  294,  295,   74,   74,  292,  293,  354,   74,
       74,   74,   74,   74,   74,  354,   74,   74,  354,  296,
       74,   74,  297,  354,  299,   74,   74,  298,  182,  354,
      182,  354,  300,  302,   74,   74,  354,  303,   74,   74,
       74,   74,   74,   74,   74,   74,  301,   74,   74,   74,

       74,  305,  354,  304,   74,   74,   74,   74,   74,   74,
       74,   74,  182,  313,  354,   74,   74,   74,   74,  354,
      308,  306,  354,  307,   74,   74,  182,  310,   74,   74,
       74,   74,  354,  309,  314,   74,   74,   74,   74,  312,
       74,   74,   74,   74,   74,   74,  354,   74,   74,   74,
       74,  354,  315,   74,   74,   74,   74,   74,   74,  319,
      354,  317,  316,  182,  318,   74,   74,  354,  182,  182,
       74,   74,  182,   74,   74,   74,   74,  354,  182,   74,
       74,   74,   74,   74,   74,   74,   74,  325,  320,   74,
       74,   74,   74,  321,  354,   74,   74,  354,  323,   74,

       74,   74,   74,  354,  322,   74,   74,   74,   74,  324,
       74,   74,  354,  182,  182,   74,   74,  354,  182,  354,
      328,  354,  329,   74,   74,  354,  330,  327,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
      182,   74,   74,  331,   74,   74,  354,  182,   74,   74,
      354,  332,  354,  182,  182,   74,   74,  354,   74,   74,
      354,  336,  354,  335,  337,   74,   74,  354,  182,  354,
      354,  182,  354,  354,  354,  354,  182,  343,  354,  354,
      354,  354,  354,  182,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  340,   59,   59,   59,   62,   62,

       62,   66,   66,   66,  144,  354,  144,  147,  147,  147,
        9,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354
    } ;

static const flex_int16_t yy_chk[1174] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    5,    6,
        7,    8,    7,    8,   25,    7,    8,    5,    6,   17,
       17,   27,   25,   26,   26,   28,   27,   28,   28,   31,
       31,   33,   33,  361,   28,   35,   35,   26,    7,    8,

      358,   28,   29,  351,   29,   29,   28,   34,   34,   26,
      350,   29,   39,   39,   40,   40,   41,   41,   29,   43,
       43,   73,   73,   29,   44,   44,   39,  349,   35,  348,
       40,   46,   46,   35,  347,   34,   42,   42,   43,  346,
       45,   45,   48,   48,  345,   41,   40,   41,   43,  344,
       44,   42,   44,  342,   41,   45,   47,   47,   42,  341,
       46,   44,   42,   45,  339,   42,   45,   49,   49,   45,
      338,   48,   50,   50,   51,   51,   47,   52,   52,   54,
       54,  334,   49,   47,   47,  333,   49,   50,  103,  103,
       53,   53,  326,   51,   54,   55,   55,   97,   97,   52,

       70,   49,   70,   50,  325,   70,   50,  103,   54,  313,
       52,   52,   53,   52,  286,   52,  253,   55,  209,   78,
       78,   53,   79,   79,  151,   85,   78,   85,   70,   97,
       85,   85,  150,   78,   95,   95,   79,   70,   78,   83,
       83,  149,   86,   86,   85,   70,   83,  144,   70,   80,
       70,   68,   84,   83,   84,   84,   86,   66,   83,   65,
       87,   84,   87,   87,   64,   89,   89,   95,   84,   87,
       96,   96,   61,   84,   57,   88,   87,   88,   88,   89,
       32,   87,   23,   98,   88,   98,   98,   19,   99,   99,
       15,   88,   98,  100,  100,   14,   88,  101,  101,   98,

        9,   96,   99,    0,   98,  102,  102,  104,  104,  105,
      105,  106,  106,  107,  107,  108,  108,  109,  109,  110,
      110,    0,  111,  111,    0,  100,  106,    0,  107,  101,
      112,  112,  113,  113,  102,  114,  114,  109,  115,  115,
      104,  105,  105,  108,  116,  116,  117,  117,  118,  118,
      119,  119,    0,  110,  111,  120,  120,  121,  121,  122,
      122,  114,  123,  123,  112,  113,  115,  124,  124,    0,
      125,  125,    0,  116,  126,  126,    0,  117,  127,  127,
        0,  118,  128,  128,    0,  120,    0,  122,    0,  121,
      121,  126,  129,  129,    0,  123,  125,    0,  128,  130,

      130,  127,    0,  124,  131,  131,    0,  127,  132,  132,
      133,  133,  134,  134,  135,  135,  136,  136,    0,  131,
      137,  137,    0,  138,  138,  129,  167,  167,  130,  139,
      139,  136,  145,  133,    0,  131,    0,  135,  132,    0,
      134,  167,  153,  153,    0,  135,  138,  154,  154,  138,
      136,  137,  139,    0,  136,  145,  153,  155,  155,  152,
      152,  154,  156,  156,  145,  157,  152,  157,  157,  158,
      158,  155,  145,  152,  157,  145,  156,  145,  152,  159,
      159,  157,  160,  160,  164,  164,  157,  161,  158,  161,
      161,    0,  162,    0,  162,    0,  161,  162,  162,  163,

      163,    0,  159,  161,  165,  165,  166,  166,  161,  168,
      168,  162,    0,  163,    0,  160,    0,  164,  169,  169,
        0,  170,  170,  165,  171,  171,  172,  172,  168,  173,
      173,    0,  166,  174,  174,  175,  175,  169,  170,    0,
      176,  176,  177,  177,  178,  178,  179,  179,  174,  180,
      180,  175,  181,  181,    0,  171,  182,  182,  172,  176,
        0,  173,  173,  178,  180,  183,  183,  181,    0,  177,
      184,  184,  185,  185,  186,  186,  187,  187,  179,  188,
      188,  189,  189,  190,  190,  191,  191,    0,  192,  192,
      193,  193,    0,  186,  183,    0,  184,  187,    0,  184,

      194,  194,  188,  196,  196,  185,    0,  189,  190,  195,
      195,    0,  197,  197,  198,  198,  193,  199,  199,    0,
      191,  192,  200,  200,  201,  201,  202,  202,    0,  203,
      203,  205,  205,  198,  194,  197,  196,  207,  207,  200,
      195,  204,  204,  206,  206,  208,  208,  210,  210,    0,
      199,    0,  207,    0,  205,  202,  201,  203,  211,  211,
      204,  206,  212,  212,  213,  213,  214,  214,  210,  215,
      215,  208,  216,  216,  217,  217,  218,  218,  213,    0,
      214,  212,  219,  219,  220,  220,  211,  221,  221,  222,
      222,  223,  223,  217,    0,  224,  224,  225,  225,    0,

      215,  218,    0,  216,  219,  226,  226,  227,  227,  228,
      228,    0,  222,  229,  229,    0,  220,  230,  230,    0,
      221,  224,  231,  231,    0,  223,  227,  232,  232,  233,
      233,  234,  234,  226,    0,  228,  230,  235,  235,  236,
      236,    0,  232,  237,  237,    0,  229,  238,  238,  239,
      239,    0,  235,  231,  236,  240,  240,    0,  241,  241,
      233,    0,  237,  243,  243,    0,  234,  242,  242,    0,
      238,    0,  244,  244,  245,  245,  246,  246,  247,  247,
      239,  241,  248,  248,  242,  249,  249,    0,  240,  244,
      250,  250,  251,  251,  243,    0,  245,  252,  252,  254,

      254,  255,  255,  256,  256,  257,  257,  258,  258,    0,
      247,    0,  246,    0,  249,    0,  252,    0,  254,    0,
      257,    0,  255,  259,  259,  251,  260,  260,  261,  261,
      256,  262,  262,  263,  263,  264,  264,    0,  259,    0,
      258,  265,  265,  266,  266,  267,  267,  268,  268,  269,
      269,    0,  263,  264,  270,  270,  261,  262,    0,  271,
      271,  272,  272,  273,  273,    0,  274,  274,    0,  266,
      275,  275,  267,    0,  270,  276,  276,  269,  271,    0,
      268,    0,  272,  274,  277,  277,    0,  275,  278,  278,
      279,  279,  280,  280,  281,  281,  273,  282,  282,  283,

      283,  277,    0,  276,  284,  284,  285,  285,  287,  287,
      288,  288,  279,  289,    0,  289,  289,  290,  290,    0,
      282,  278,    0,  280,  291,  291,  281,  284,  292,  292,
      293,  293,    0,  283,  290,  294,  294,  295,  295,  287,
      296,  296,  297,  297,  299,  299,    0,  298,  298,  300,
      300,    0,  291,  301,  301,  302,  302,  303,  303,  299,
        0,  297,  292,  293,  298,  304,  304,    0,  300,  295,
      305,  305,  301,  306,  306,  307,  307,    0,  296,  308,
      308,  309,  309,  310,  310,  314,  314,  312,  302,  312,
      312,  315,  315,  306,    0,  316,  316,    0,  308,  317,

      317,  318,  318,    0,  307,  319,  319,  320,  320,  310,
      321,  321,    0,  309,  316,  322,  322,    0,  314,    0,
      318,    0,  319,  323,  323,    0,  320,  317,  324,  324,
      327,  327,  328,  328,  329,  329,  330,  330,  332,  332,
      321,  331,  331,  322,  335,  335,    0,  324,  336,  336,
        0,  323,    0,  329,  330,  337,  337,    0,  340,  340,
        0,  328,    0,  327,  331,  343,  343,    0,  336,    0,
        0,  332,    0,    0,    0,    0,  335,  340,    0,    0,
        0,    0,    0,  343,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  337,  355,  355,  355,  356,  356,

      356,  357,  357,  357,  359,    0,  359,  360,  360,  360,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
/*
Miguel Filipe de Andrade Sergio 2020225643
Filipe David Amado Mendes 2020218797
*/
#line 824 "lex.yy.c"
#line 19 "jucompiler.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <stdbool.h>
	#include <string.h>
	#include <stdarg.h>
    #include "functions.h"
	#include "y.tab.h"

    int line = 1, column = 1;
    int column_aux = 1;
    int line_aux = 1;
    char * buffer;
    bool buffer_flag = true; 
	int flag = 0;
	extern int flag_error;
#line 841 "lex.yy.c"

#line 843 "lex.yy.c"

#define INITIAL 0
#define SINGLECOMM 1
#define MULTPLECOMM 2
#define SLIT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "jucompiler.l"


#line 1066 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 355 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1111 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{BEGIN SINGLECOMM;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "jucompiler.l"
{line++; column = 1; BEGIN 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{line_aux =  line; column_aux = column; column += yyleng; BEGIN MULTPLECOMM;}  
	YY_BREAK
case YY_STATE_EOF(MULTPLECOMM):
#line 45 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", line_aux, column_aux); exit(0);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{column += yyleng; line_aux = 1; column_aux = 1; BEGIN 0;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 47 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{buffer=yytext; line_aux =  line; column_aux = column; column += yyleng; buffer_flag = true;  BEGIN STRLIT;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 51 "jucompiler.l"
{column=1; printf("Line %d, col %d: unterminated string literal\n",  line, column_aux); line++; column = 1;  BEGIN 0;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 53 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\)\nLine %d, col %d: unterminated string literal\n", line, column, line, column_aux); column = 1; line++; buffer_flag = false; BEGIN 0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\)\n", line, column); column += yyleng; buffer_flag = false; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",  line, column, yytext); column += yyleng; buffer_flag = false; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{column += yyleng; if (buffer_flag && flag) {printf("STRLIT(%s)\n", buffer); buffer_flag = true; } BEGIN 0;
										if(flag != 1 && flag_error == 0) {
											yylval.id = strdup(buffer);
											yytext = buffer;
											return STRLIT;
										}
									}
	YY_BREAK
case YY_STATE_EOF(SLIT):
#line 63 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",  line, column_aux); exit(0);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if (flag) printf("BOOLLIT(false)\n"); column += yyleng; 
										if(flag != 1){
											yylval.id = strdup(yytext);
											return BOOLLIT;
										} 
									}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if (flag) printf("BOOLLIT(true)\n"); column += yyleng;
										if(flag != 1){
											yylval.id = strdup(yytext);
											return BOOLLIT;
										} 
									} 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if (flag) printf("AND\n"); column += yyleng; if(flag != 1) return AND; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if (flag) printf("ASSIGN\n"); column += yyleng; if(flag != 1) return ASSIGN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if (flag) printf("STAR\n"); column += yyleng; if(flag != 1) return STAR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if (flag) printf("COMMA\n"); column += yyleng; if(flag != 1) return COMMA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if (flag) printf("DIV\n"); column += yyleng; if(flag != 1) return DIV; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if (flag) printf("EQ\n"); column += yyleng; if(flag != 1) return EQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if (flag) printf("GE\n"); column += yyleng; if(flag != 1) return GE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if (flag) printf("GT\n"); column += yyleng; if(flag != 1) return GT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if (flag) printf("LBRACE\n"); column += yyleng; if(flag != 1) return LBRACE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if (flag) printf("LE\n"); column += yyleng; if(flag != 1) return LE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if (flag) printf("LPAR\n"); column += yyleng; if(flag != 1) return LPAR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if (flag) printf("LSQ\n"); column += yyleng; if(flag != 1) return LSQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if (flag) printf("LT\n"); column += yyleng; if(flag != 1) return LT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if (flag) printf("MINUS\n"); column += yyleng; if(flag != 1) return MINUS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if (flag) printf("MOD\n"); column += yyleng; if(flag != 1) return MOD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if (flag) printf("NE\n"); column += yyleng; if(flag != 1) return NE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if (flag) printf("NOT\n"); column += yyleng; if(flag != 1) return NOT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if (flag) printf("OR\n"); column += yyleng; if(flag != 1) return OR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if (flag) printf("PLUS\n"); column += yyleng; if(flag != 1) return PLUS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if (flag) printf("RBRACE\n"); column += yyleng; if(flag != 1) return RBRACE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if (flag) printf("RPAR\n"); column += yyleng; if(flag != 1) return RPAR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if (flag) printf("RSQ\n"); column += yyleng; if(flag != 1) return RSQ; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if (flag) printf("SEMICOLON\n"); column += yyleng; if(flag != 1) return SEMICOLON; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if (flag) printf("ARROW\n"); column += yyleng; if(flag != 1) return ARROW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if (flag) printf("LSHIFT\n"); column += yyleng; if(flag != 1) return LSHIFT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if (flag) printf("RSHIFT\n"); column += yyleng; if(flag != 1) return RSHIFT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{if (flag) printf("XOR\n"); column += yyleng; if(flag != 1) return XOR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{if (flag) printf("BOOL\n"); column += yyleng; if(flag != 1) return BOOL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if (flag) printf("CLASS\n"); column += yyleng; if(flag != 1) return CLASS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{if (flag) printf("DOTLENGTH\n"); column += yyleng; if(flag != 1) return DOTLENGTH; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{if (flag) printf("DOUBLE\n"); column += yyleng; if(flag != 1) return DOUBLE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{if (flag) printf("ELSE\n"); column += yyleng; if(flag != 1) return ELSE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{if (flag) printf("IF\n"); column += yyleng; if(flag != 1) return IF; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{if (flag) printf("INT\n"); column += yyleng; if(flag != 1) return INT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if (flag) printf("PRINT\n"); column += yyleng; if(flag != 1) return PRINT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if (flag) printf("PARSEINT\n"); column += yyleng; if(flag != 1) return PARSEINT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if (flag) printf("PUBLIC\n"); column += yyleng; if(flag != 1) return PUBLIC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{if (flag) printf("RETURN\n"); column += yyleng; if(flag != 1) return RETURN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if (flag) printf("STATIC\n"); column += yyleng; if(flag != 1) return STATIC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if (flag) printf("STRING\n"); column += yyleng; if(flag != 1) return STRING; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if (flag) printf("VOID\n"); column += yyleng; if(flag != 1) return VOID; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if (flag) printf("WHILE\n"); column += yyleng; if(flag != 1) return WHILE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{if (flag) printf("RESERVED(%s)\n", yytext); column += yyleng;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "jucompiler.l"
{column += yyleng; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{column += yyleng; }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 124 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "jucompiler.l"
{if (flag) printf("ID(%s)\n", yytext); column += yyleng; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "jucompiler.l"
{if (flag) printf("INTLIT(%s)\n", yytext); column += yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return INTLIT;
										} 
									}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{if (flag) printf("REALLIT(%s)\n", yytext); column += yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return REALLIT;
										}
									}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", line, column, yytext); column += yyleng; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLECOMM):
#line 140 "jucompiler.l"
{column = 1; exit(0);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 142 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1502 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 355 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 355 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 354);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 142 "jucompiler.l"



int yywrap() {
	return 1;
}

void yyerror(const char *s) { 
     printf ("Line %d, col %d: %s: %s\n", line, (int)(column-strlen(yytext)), s, yytext);
}


int main(int argc, char *argv[]) {
	if (argc > 1) {
		if (strcmp(argv[1],"-l") == 0) {
			flag = 1;
			yyparse();
		}
		else if (strcmp(argv[1],"-t") == 0) {
			// análise lexical, análise sintatica e PRINT TREE
			flag = 2;
			yyparse();
		}
		else if (strcmp(argv[1], "-e1") == 0) {
			flag = 0;
			while (yylex() != 0) {
				;
			}
		}
		else if (strcmp(argv[1], "-e2") == 0) {
			flag = 0;
			flag_error = 1;
			yyparse();
			yylex();
		}
	}
}
