
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[350] =
    {   0,
        0,    0,    0,    0,    0,    0,   10,   10,   68,   66,
       60,   62,   61,   62,   33,    8,   63,   31,   66,   27,
       37,   19,   35,   20,   30,   66,   21,   64,   64,   39,
       29,   18,   24,   63,   63,   28,   38,   43,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   25,   66,   36,    3,    2,
        2,    7,    6,    6,    7,   10,    9,    9,   14,   12,
       62,   32,   63,   63,   17,   59,   40,   65,    0,    0,
        4,    1,   65,    0,    0,    0,   64,   64,    0,   41,
       26,   22,   23,   42,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,   63,   59,
       63,   63,   63,   63,   63,   63,   63,   63,   49,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   34,    2,
        6,    5,   10,    0,    9,   13,   11,   11,   10,    0,
       65,    0,    0,   65,    0,   64,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       59,   63,   63,   63,   50,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,    0,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   48,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   16,   57,   63,   63,    0,
       63,   63,   63,   63,   63,   63,   45,   63,   63,   63,
       63,   15,   59,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   59,   63,   63,
       58,    0,   63,   56,   59,   63,   63,   63,   63,   47,
       63,   63,   63,   63,   63,   63,   63,   63,   53,   54,

       55,   63,   63,   63,   63,   46,   59,    0,   63,   44,
       63,   63,   63,   63,   63,   63,   63,   63,   63,    0,
        0,   63,   63,   63,   63,   63,   63,    0,    0,   63,
       63,   63,    0,    0,   63,    0,    0,   63,    0,    0,
        0,    0,    0,    0,    0,    0,   52,   51,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    2,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[357] =
    {   0,
        0,    0,   60,   61,   64,   65,   68,   69,  366, 1083,
     1083, 1083, 1083,  357,  331, 1083,   60, 1083,  337, 1083,
     1083, 1083,  331, 1083,   58,   64,   68,   68,   85, 1083,
       67,  318,   68,   88,   76, 1083, 1083, 1083,   93,   95,
       97,  117,  100,  105,  121,  112,  137,  123,  148,  153,
      155,  158,  171,  160,  175, 1083,  273, 1083, 1083, 1083,
      324, 1083, 1083,  301,  274,  258, 1083,  283, 1083,  198,
     1083, 1083,  102,    0, 1083, 1083, 1083,  198,  200,  239,
     1083, 1083,  206,  221,  237,  210,  241,  245,  249, 1083,
     1083, 1083, 1083, 1083,  203,  177,  215,  267,  256,  253,

      261,  271,  169,  275,  277,  279,  282,  287,  291,  289,
      295,  298,  301,  303,  305,  312,  316,  318,  320,  324,
      330,  336,  338,  342,  344,  348,  352,  356,  358,  360,
      367,  373,  376,  379,  383,  385,  387,  392, 1083, 1083,
     1083, 1083,  233,  406, 1083, 1083, 1083,  250,  219,  199,
      411,  395,  421,  427,  431,  442,  401,  446,  450,  457,
      465,  453,  472,  474,  477,  480,  485,  487,  490,  496,
      404,  498,  500,  508,  510,  512,  516,  518,  521,  525,
      532,  537,  541,  543,  545,  547,  551,  553,  555,  557,
      560,  562,  571,  577,  581,  583,  585,  589,  594,  596,

      598,  601,  612,  615,  609,  617,  202,  619,  625,  635,
      637,  641,  644,  646,  648,  656,  658,  660,  662,  664,
      668,  670,  672,  678,  682,  684,  688,  690,  693,  697,
      699,  703,  707,  713,  715,  717,  719,  725,  731,  735,
      741,  743,  745,  747,  755,  761,  763,  765,  769,  162,
      773,  775,  777,  779,  781,  784,  789,  800,  805,  802,
      807,  809,  811,  815,  817,  819,  823,  826,  832,  829,
      834,  838,  840,  848,  856,  858,  860,  863,  869,  871,
      866,  168,  873,  875,  881,  883,  877,  885,  887,  896,
      898,  901,  906,  909,  912,  914,  916,  921,  923,  928,

      931,  936,  940,  942,  944, 1083,  948,  156,  950,  952,
      957,  959,  962,  965,  967,  971,  974,  977,  979,  149,
      139,  984,  989,  991,  993,  996,  999,  151,  129, 1003,
     1006, 1008,  120,  147, 1012,  108,  104, 1015,  111,   94,
      112,   92,   82,   80,   58,   51, 1083, 1083, 1083, 1067,
     1070, 1073,   98, 1076, 1079,   91
    } ;

static const flex_int16_t yy_def[357] =
    {   0,
      349,    1,  350,  350,  351,  351,  352,  352,  349,  349,
      349,  349,  349,  349,  349,  349,  353,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  353,  353,  349,  349,  349,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  354,  349,  349,  349,  355,
      349,  349,  353,  356,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  353,  353,  353,  356,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  349,  349,
      349,  349,  354,  349,  349,  349,  349,  349,  354,  349,
      349,  349,  349,  349,  349,  349,  353,  353,  353,  356,
      356,  356,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  349,  353,  353,  353,
      356,  356,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  349,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  349,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  349,  353,  349,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  349,
      349,  353,  353,  353,  353,  353,  353,  349,  349,  353,
      353,  353,  349,  349,  353,  349,  349,  353,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,    0,  349,
      349,  349,  349,  349,  349,  349
    } ;

static const flex_int16_t yy_nxt[1146] =
    {   0,
       10,   11,   12,   13,   14,   11,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   17,   17,   34,   35,   36,
       10,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   17,   47,   17,   17,   48,   17,   49,   17,   50,
       51,   52,   53,   17,   54,   55,   17,   17,   17,   56,
       57,   58,   60,   60,   61,   61,   63,   63,   64,   64,
       67,   67,   68,   68,   76,   69,   69,   65,   65,   74,
       74,   81,   77,   78,   78,   83,   82,   84,   84,   90,
       91,   93,   94,   74,   85,   74,   74,   79,   70,   70,

       73,   86,   83,  348,   87,   88,   85,   74,   74,   80,
      347,   85,   98,   98,   74,   74,   74,   74,   89,   74,
       74,   74,   74,   85,   74,   74,   99,  346,   96,  345,
      100,   74,   74,   97,  344,   95,   74,   74,  109,  343,
       74,   74,   74,   74,  342,  102,  101,  103,  110,  341,
      111,  105,  112,  340,  104,  114,   74,   74,  106,  339,
      118,  113,  107,  115,  337,  108,  116,   74,   74,  117,
      336,  122,   74,   74,   74,   74,  119,   74,   74,   74,
       74,  334,  123,  120,  121,  333,  124,  126,   74,   74,
       74,   74,  329,  129,   74,   74,   74,   74,  328,  130,

      147,  125,  148,  127,  321,  149,  128,  166,  137,  306,
      131,  132,  135,  133,  282,  134,  138,   78,   78,   78,
       78,  136,   74,   74,   85,  151,  151,  158,  149,   84,
       84,   79,   85,   79,   74,   74,   85,  149,   83,  152,
       84,   84,  250,   86,   85,  149,  207,   85,  149,  144,
      149,  153,  147,  153,   86,  157,  154,  154,   83,   85,
       87,   87,   83,  144,   87,   88,  159,   85,  156,  156,
      155,   85,   74,   74,   89,   98,   98,  150,   89,   85,
       74,   74,   89,   85,   83,  145,  160,  160,  144,   99,
       74,   74,  142,  161,   74,   74,   74,   74,   74,   74,

      162,   74,   74,  141,  163,  161,   74,   74,   74,   74,
       74,   74,  164,  170,   74,   74,  171,   74,   74,  165,
       74,   74,   74,   74,   74,   74,  140,  167,  168,  169,
      173,   74,   74,  139,  172,   74,   74,   74,   74,   74,
       74,   92,  174,   74,   74,   76,  175,   75,  178,   74,
       74,  176,  179,  177,   72,   74,   74,   74,   74,   71,
      180,   74,   74,   74,   74,  349,  181,   74,   74,  349,
      182,   74,   74,  183,  349,   74,   74,   74,   74,   74,
       74,  184,  185,  186,  189,  349,   74,   74,  349,  188,
      187,  192,   74,   74,  190,   74,   74,  181,   74,   74,

      191,  195,   74,   74,   74,   74,   74,   74,  194,  349,
      193,   74,   74,  143,  151,  151,  349,  196,  198,  202,
       74,   74,  197,   74,   74,  200,  199,  349,  152,  204,
      151,  151,  205,  201,  206,  349,  143,   85,  203,  208,
      154,  154,  181,  349,  152,  143,  154,  154,  349,   85,
      154,  154,  349,  143,  155,  218,  143,  349,  143,   83,
      155,   87,   87,  349,  155,   74,   74,  349,   85,   74,
       74,  349,  160,  160,   83,   89,  160,  160,  349,  153,
       85,  153,  349,  161,  211,  211,  162,  349,  209,  349,
      162,   74,   74,   74,   74,  161,   74,   74,  212,   74,

       74,  349,  210,  349,   74,   74,   74,   74,  349,   74,
       74,  349,  214,  349,  216,   74,   74,   74,   74,   74,
       74,  349,  215,  181,  213,  181,  217,   74,   74,   74,
       74,   74,   74,  349,  221,   74,   74,   74,   74,  349,
       74,   74,  349,  222,   74,   74,  181,  349,  223,  219,
      220,   74,   74,  349,  224,  226,   74,   74,  181,  227,
       74,   74,   74,   74,   74,   74,   74,   74,  349,  225,
       74,   74,   74,   74,   74,   74,   74,   74,  349,   74,
       74,   74,   74,  231,  349,  181,  228,  181,  349,  229,
       74,   74,  349,  232,  349,  230,   74,   74,  181,  233,

       74,   74,   74,   74,   74,   74,  349,  236,   74,   74,
      349,  234,  235,   74,   74,   74,   74,   74,   74,  349,
       74,   74,  349,  241,  237,  240,  349,  238,   74,   74,
      243,   74,   74,  239,   74,   74,   74,   74,   74,   74,
      349,  242,  349,  248,   74,   74,  244,  181,  245,  349,
      246,  349,  247,  349,   74,   74,  211,  211,  349,  251,
      211,  211,  249,   74,   74,   74,   74,   74,   74,  349,
      212,  349,  252,  253,  212,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,  349,  256,   74,   74,   74,
       74,   74,   74,  349,  254,  349,  255,   74,   74,  181,

      181,   74,   74,   74,   74,  349,  258,   74,   74,   74,
       74,  257,   74,   74,  181,  260,   74,   74,   74,   74,
      262,  259,   74,   74,  349,  261,   74,   74,  264,  263,
      349,  266,   74,   74,   74,   74,   74,   74,   74,   74,
      181,  269,  349,  265,   74,   74,  349,  270,  349,  267,
       74,   74,  349,  271,   74,   74,  349,  268,  349,  272,
       74,   74,   74,   74,   74,   74,   74,   74,  349,  273,
      349,  275,  349,  274,   74,   74,  349,  181,  349,  276,
       74,   74,   74,   74,   74,   74,  277,  349,   74,   74,
      349,  181,   74,   74,   74,   74,   74,   74,   74,   74,

       74,   74,  278,   74,   74,  349,  279,  281,   74,   74,
      349,  283,  349,  286,  349,  284,  349,  280,  287,   74,
       74,   74,   74,  285,   74,   74,   74,   74,   74,   74,
       74,   74,  349,  181,   74,   74,   74,   74,   74,   74,
      290,  349,   74,   74,  291,   74,   74,  288,   74,   74,
      289,   74,   74,   74,   74,  349,  292,   74,   74,   74,
       74,  293,  295,  349,  181,  349,  294,   74,   74,  181,
      298,  349,  296,  349,  299,   74,   74,   74,   74,   74,
       74,  297,   74,   74,  301,   74,   74,  300,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,  308,  181,

       74,   74,   74,   74,   74,   74,   74,   74,  302,  349,
      303,  304,  349,  305,  181,   74,   74,   74,   74,  309,
       74,   74,  349,  307,  310,   74,   74,  349,   74,   74,
      349,   74,   74,   74,   74,   74,   74,  349,  311,  181,
       74,   74,   74,   74,  312,  313,  314,   74,   74,  181,
       74,   74,  181,  349,  181,   74,   74,  349,  181,   74,
       74,   74,   74,   74,   74,  320,  349,   74,   74,   74,
       74,   74,   74,  315,  349,  316,   74,   74,   74,   74,
      318,   74,   74,  349,   74,   74,   74,   74,  317,  319,
       74,   74,  349,   74,   74,  181,   74,   74,   74,   74,

      323,  324,  181,   74,   74,  325,  322,  349,   74,   74,
       74,   74,   74,   74,  349,   74,   74,  181,   74,   74,
      181,  326,   74,   74,  327,   74,   74,   74,   74,  181,
      181,   74,   74,  349,   74,   74,  330,  331,  332,  349,
      349,  349,  349,  349,  349,  181,  349,  349,  349,  349,
      338,  181,  181,  349,  181,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  335,   59,   59,   59,
       62,   62,   62,   66,   66,   66,  143,  349,  143,  146,
      146,  146,    9,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349
    } ;

static const flex_int16_t yy_chk[1146] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    5,    6,
        7,    8,    7,    8,   25,    7,    8,    5,    6,   17,
       17,   27,   25,   26,   26,   28,   27,   28,   28,   31,
       31,   33,   33,  356,   28,   35,   35,   26,    7,    8,

      353,   28,   29,  346,   29,   29,   28,   34,   34,   26,
      345,   29,   39,   39,   40,   40,   41,   41,   29,   43,
       43,   73,   73,   29,   44,   44,   39,  344,   35,  343,
       40,   46,   46,   35,  342,   34,   42,   42,   43,  341,
       45,   45,   48,   48,  340,   41,   40,   41,   43,  339,
       44,   42,   44,  337,   41,   45,   47,   47,   42,  336,
       46,   44,   42,   45,  334,   42,   45,   49,   49,   45,
      333,   48,   50,   50,   51,   51,   47,   52,   52,   54,
       54,  329,   49,   47,   47,  328,   49,   50,  103,  103,
       53,   53,  321,   51,   55,   55,   96,   96,  320,   52,

       70,   49,   70,   50,  308,   70,   50,  103,   54,  282,
       52,   52,   53,   52,  250,   52,   55,   78,   78,   79,
       79,   53,   95,   95,   78,   83,   83,   96,   70,   86,
       86,   78,   83,   79,   97,   97,   78,   70,   84,   83,
       84,   84,  207,   86,   83,   70,  150,   84,   70,  149,
       70,   85,  148,   85,   84,   95,   85,   85,   87,   84,
       87,   87,   88,  143,   88,   88,   97,   87,   89,   89,
       85,   88,  100,  100,   87,   99,   99,   80,   88,   87,
      101,  101,   89,   88,   98,   68,   98,   98,   66,   99,
      102,  102,   65,   98,  104,  104,  105,  105,  106,  106,

       98,  107,  107,   64,  100,   98,  108,  108,  110,  110,
      109,  109,  101,  106,  111,  111,  107,  112,  112,  102,
      113,  113,  114,  114,  115,  115,   61,  104,  105,  105,
      109,  116,  116,   57,  108,  117,  117,  118,  118,  119,
      119,   32,  110,  120,  120,   23,  111,   19,  114,  121,
      121,  112,  115,  113,   15,  122,  122,  123,  123,   14,
      116,  124,  124,  125,  125,    9,  117,  126,  126,    0,
      118,  127,  127,  120,    0,  128,  128,  129,  129,  130,
      130,  121,  121,  122,  126,    0,  131,  131,    0,  125,
      123,  128,  132,  132,  127,  133,  133,  124,  134,  134,

      127,  131,  135,  135,  136,  136,  137,  137,  130,    0,
      129,  138,  138,  144,  152,  152,    0,  131,  133,  136,
      157,  157,  132,  171,  171,  135,  134,    0,  152,  137,
      151,  151,  137,  135,  138,    0,  144,  151,  136,  157,
      153,  153,  136,    0,  151,  144,  154,  154,    0,  151,
      155,  155,    0,  144,  153,  171,  144,    0,  144,  156,
      154,  156,  156,    0,  155,  158,  158,    0,  156,  159,
      159,    0,  162,  162,  160,  156,  160,  160,    0,  161,
      156,  161,    0,  160,  161,  161,  162,    0,  158,    0,
      160,  163,  163,  164,  164,  160,  165,  165,  161,  166,

      166,    0,  159,    0,  167,  167,  168,  168,    0,  169,
      169,    0,  164,    0,  166,  170,  170,  172,  172,  173,
      173,    0,  165,  167,  163,  168,  169,  174,  174,  175,
      175,  176,  176,    0,  173,  177,  177,  178,  178,    0,
      179,  179,    0,  174,  180,  180,  170,    0,  175,  172,
      172,  181,  181,    0,  177,  179,  182,  182,  176,  180,
      183,  183,  184,  184,  185,  185,  186,  186,    0,  178,
      187,  187,  188,  188,  189,  189,  190,  190,    0,  191,
      191,  192,  192,  185,    0,  182,  183,  186,    0,  183,
      193,  193,    0,  187,    0,  184,  194,  194,  188,  189,

      195,  195,  196,  196,  197,  197,    0,  192,  198,  198,
        0,  190,  191,  199,  199,  200,  200,  201,  201,    0,
      202,  202,    0,  197,  193,  196,    0,  194,  205,  205,
      199,  203,  203,  195,  204,  204,  206,  206,  208,  208,
        0,  198,    0,  205,  209,  209,  201,  200,  202,    0,
      203,    0,  204,    0,  210,  210,  211,  211,    0,  208,
      212,  212,  206,  213,  213,  214,  214,  215,  215,    0,
      211,    0,  209,  210,  212,  216,  216,  217,  217,  218,
      218,  219,  219,  220,  220,    0,  215,  221,  221,  222,
      222,  223,  223,    0,  213,    0,  214,  224,  224,  217,

      216,  225,  225,  226,  226,    0,  220,  227,  227,  228,
      228,  218,  229,  229,  219,  222,  230,  230,  231,  231,
      225,  221,  232,  232,    0,  224,  233,  233,  228,  226,
        0,  230,  234,  234,  235,  235,  236,  236,  237,  237,
      227,  233,    0,  229,  238,  238,    0,  234,    0,  231,
      239,  239,    0,  235,  240,  240,    0,  232,    0,  236,
      241,  241,  242,  242,  243,  243,  244,  244,    0,  237,
        0,  240,    0,  239,  245,  245,    0,  238,    0,  242,
      246,  246,  247,  247,  248,  248,  243,    0,  249,  249,
        0,  241,  251,  251,  252,  252,  253,  253,  254,  254,

      255,  255,  244,  256,  256,    0,  245,  249,  257,  257,
        0,  251,    0,  254,    0,  252,    0,  248,  256,  258,
      258,  260,  260,  253,  259,  259,  261,  261,  262,  262,
      263,  263,    0,  255,  264,  264,  265,  265,  266,  266,
      260,    0,  267,  267,  261,  268,  268,  258,  270,  270,
      259,  269,  269,  271,  271,    0,  263,  272,  272,  273,
      273,  264,  267,    0,  268,    0,  266,  274,  274,  265,
      271,    0,  269,    0,  272,  275,  275,  276,  276,  277,
      277,  270,  278,  278,  274,  281,  281,  273,  279,  279,
      280,  280,  283,  283,  284,  284,  287,  287,  285,  276,

      285,  285,  286,  286,  288,  288,  289,  289,  275,    0,
      277,  279,    0,  280,  278,  290,  290,  291,  291,  286,
      292,  292,    0,  283,  287,  293,  293,    0,  294,  294,
        0,  295,  295,  296,  296,  297,  297,    0,  288,  289,
      298,  298,  299,  299,  293,  294,  295,  300,  300,  291,
      301,  301,  296,    0,  297,  302,  302,    0,  292,  303,
      303,  304,  304,  305,  305,  307,    0,  307,  307,  309,
      309,  310,  310,  298,    0,  302,  311,  311,  312,  312,
      304,  313,  313,    0,  314,  314,  315,  315,  303,  305,
      316,  316,    0,  317,  317,  311,  318,  318,  319,  319,

      313,  314,  309,  322,  322,  315,  312,    0,  323,  323,
      324,  324,  325,  325,    0,  326,  326,  319,  327,  327,
      316,  317,  330,  330,  318,  331,  331,  332,  332,  324,
      325,  335,  335,    0,  338,  338,  322,  323,  326,    0,
        0,    0,    0,    0,    0,  331,    0,    0,    0,    0,
      335,  327,  338,    0,  330,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  332,  350,  350,  350,
      351,  351,  351,  352,  352,  352,  354,    0,  354,  355,
      355,  355,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
/*
Miguel Filipe de Andrade Sergio 2020225643
Filipe David Amado Mendes 2020218797
*/
#line 815 "lex.yy.c"
#line 19 "jucompiler.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <stdbool.h>
	#include <string.h>
	#include <stdarg.h>
    #include "functions.h"
	#include "y.tab.h"

    int line = 1, column = 1;
    int column_aux = 1;
    int line_aux = 1;
    char * buffer;
    bool buffer_flag = true; 
	int flag = 0;
	extern int flag_error;
#line 832 "lex.yy.c"

#line 834 "lex.yy.c"

#define INITIAL 0
#define SINGLECOMM 1
#define MULTPLECOMM 2
#define SLIT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "jucompiler.l"


#line 1057 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 350 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1083 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{BEGIN SINGLECOMM;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "jucompiler.l"
{line++; column = 1; BEGIN 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{line_aux =  line; column_aux = column; column += yyleng; BEGIN MULTPLECOMM;}  
	YY_BREAK
case YY_STATE_EOF(MULTPLECOMM):
#line 45 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", line_aux, column_aux); exit(0);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{column += yyleng; line_aux = 1; column_aux = 1; BEGIN 0;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 47 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{buffer=yytext; line_aux =  line; column_aux = column; column += yyleng; buffer_flag = true;  BEGIN STRLIT;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 51 "jucompiler.l"
{column=1; printf("Line %d, col %d: unterminated string literal\n",  line, column_aux); line++; column = 1;  BEGIN 0;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 53 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\)\nLine %d, col %d: unterminated string literal\n", line, column, line, column_aux); column = 1; line++; buffer_flag = false; BEGIN 0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\)\n", line, column); column += yyleng; buffer_flag = false; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",  line, column, yytext); column += yyleng; buffer_flag = false; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{column += yyleng; if (buffer_flag && flag) {printf("STRLIT(%s)\n", buffer); buffer_flag = true; } BEGIN 0;
										if(flag != 1 && flag_error == 0) {
											yylval.id = strdup(buffer);
											yytext = buffer;
											return STRLIT;
										}
									}
	YY_BREAK
case YY_STATE_EOF(SLIT):
#line 63 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",  line, column_aux); exit(0);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if (flag) printf("BOOLLIT(false)\n"); column += yyleng; 
										if(flag != 1){
											yylval.id = strdup(yytext);
											return BOOLLIT;
										} 
									}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if (flag) printf("BOOLLIT(true)\n"); column += yyleng;
										if(flag != 1){
											yylval.id = strdup(yytext);
											return BOOLLIT;
										} 
									} 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if (flag) printf("AND\n"); column += yyleng; if(flag != 1) return AND; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if (flag) printf("ASSIGN\n"); column += yyleng; if(flag != 1) return ASSIGN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if (flag) printf("STAR\n"); column += yyleng; if(flag != 1) return STAR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if (flag) printf("COMMA\n"); column += yyleng; if(flag != 1) return COMMA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if (flag) printf("DIV\n"); column += yyleng; if(flag != 1) return DIV; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if (flag) printf("EQ\n"); column += yyleng; if(flag != 1) return EQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if (flag) printf("GE\n"); column += yyleng; if(flag != 1) return GE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if (flag) printf("GT\n"); column += yyleng; if(flag != 1) return GT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if (flag) printf("LBRACE\n"); column += yyleng; if(flag != 1) return LBRACE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if (flag) printf("LE\n"); column += yyleng; if(flag != 1) return LE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if (flag) printf("LPAR\n"); column += yyleng; if(flag != 1) return LPAR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if (flag) printf("LSQ\n"); column += yyleng; if(flag != 1) return LSQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if (flag) printf("LT\n"); column += yyleng; if(flag != 1) return LT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if (flag) printf("MINUS\n"); column += yyleng; if(flag != 1) return MINUS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if (flag) printf("MOD\n"); column += yyleng; if(flag != 1) return MOD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if (flag) printf("NE\n"); column += yyleng; if(flag != 1) return NE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if (flag) printf("NOT\n"); column += yyleng; if(flag != 1) return NOT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if (flag) printf("OR\n"); column += yyleng; if(flag != 1) return OR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if (flag) printf("PLUS\n"); column += yyleng; if(flag != 1) return PLUS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if (flag) printf("RBRACE\n"); column += yyleng; if(flag != 1) return RBRACE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if (flag) printf("RPAR\n"); column += yyleng; if(flag != 1) return RPAR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if (flag) printf("RSQ\n"); column += yyleng; if(flag != 1) return RSQ; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if (flag) printf("SEMICOLON\n"); column += yyleng; if(flag != 1) return SEMICOLON; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if (flag) printf("ARROW\n"); column += yyleng; if(flag != 1) return ARROW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if (flag) printf("LSHIFT\n"); column += yyleng; if(flag != 1) return LSHIFT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if (flag) printf("RSHIFT\n"); column += yyleng; if(flag != 1) return RSHIFT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{if (flag) printf("XOR\n"); column += yyleng; if(flag != 1) return XOR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{if (flag) printf("BOOL\n"); column += yyleng; if(flag != 1) return BOOL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if (flag) printf("CLASS\n"); column += yyleng; if(flag != 1) return CLASS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{if (flag) printf("DOTLENGTH\n"); column += yyleng; if(flag != 1) return DOTLENGTH; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{if (flag) printf("DOUBLE\n"); column += yyleng; if(flag != 1) return DOUBLE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{if (flag) printf("ELSE\n"); column += yyleng; if(flag != 1) return ELSE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{if (flag) printf("IF\n"); column += yyleng; if(flag != 1) return IF; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{if (flag) printf("INT\n"); column += yyleng; if(flag != 1) return INT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if (flag) printf("PRINT\n"); column += yyleng; if(flag != 1) return PRINT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if (flag) printf("PARSEINT\n"); column += yyleng; if(flag != 1) return PARSEINT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if (flag) printf("PUBLIC\n"); column += yyleng; if(flag != 1) return PUBLIC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{if (flag) printf("RETURN\n"); column += yyleng; if(flag != 1) return RETURN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if (flag) printf("STATIC\n"); column += yyleng; if(flag != 1) return STATIC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if (flag) printf("STRING\n"); column += yyleng; if(flag != 1) return STRING; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if (flag) printf("VOID\n"); column += yyleng; if(flag != 1) return VOID; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if (flag) printf("WHILE\n"); column += yyleng; if(flag != 1) return WHILE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{if (flag) printf("RESERVED(%s)\n", yytext); column += yyleng;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 124 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "jucompiler.l"
{if (flag) printf("ID(%s)\n", yytext); column += yyleng; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "jucompiler.l"
{if (flag) printf("INTLIT(%s)\n", yytext); column += yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return INTLIT;
										} 
									}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{if (flag) printf("REALLIT(%s)\n", yytext); column += yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return REALLIT;
										}
									}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", line, column, yytext); column += yyleng; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLECOMM):
#line 140 "jucompiler.l"
{column = 1; exit(0);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 142 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1493 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 350 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 350 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 349);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 142 "jucompiler.l"



int yywrap() {
	return 1;
}

void yyerror(const char *s) { 
     printf ("Line %d, col %d: %s: %s\n", line, (int)(column-strlen(yytext)), s, yytext);
}


int main(int argc, char *argv[]) {
	if (argc > 1) {
		if (strcmp(argv[1],"-l") == 0) {
			flag = 2;
		}
		else if (strcmp(argv[1],"-t") == 0) {
			flag = 2;
			yyparse();
		}
		else if (strcmp(argv[1], "-e1") == 0) {
			flag = 0;
			while (yylex() != 0) {
				;
			}
		}
		else if (strcmp(argv[1], "-e2") == 0) {
			flag = 0;
			flag_error = 1;
			yyparse();
			yylex();
		}
	}
}

