
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[373] =
    {   0,
        0,    0,    0,    0,    0,    0,    9,    9,   66,   64,
       57,   60,   59,   60,   58,   29,    8,   61,   27,   64,
       23,   33,   15,   31,   16,   26,   64,   17,   62,   62,
       35,   25,   14,   20,   61,   61,   24,   34,   39,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   21,   64,   32,    3,
        2,    2,    7,    6,    6,    7,    9,   11,   11,   12,
       10,   60,   28,   61,   61,   13,   56,   36,   63,    0,
        0,    4,    1,   63,    0,    0,    0,   62,   62,    0,
       37,   22,   18,   19,   38,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       56,   61,   61,   61,   61,   61,   61,   61,   61,   45,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       30,    2,    6,    5,    9,    0,   11,   10,    9,   63,
        0,    0,   63,    0,   63,    0,    0,   63,    0,   62,
       61,   61,   61,    0,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   56,   61,   61,   61,   46,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   63,   63,    0,    0,   63,    0,   63,   63,    0,
        0,   62,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   44,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   55,   61,
       53,   61,   61,   63,   63,    0,   63,   63,   63,   61,
       61,   61,   61,   61,   61,   41,   61,   61,   61,   61,
       56,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   56,   61,   61,   61,   54,

       63,    0,   63,   63,   61,   52,   56,   61,   61,   61,
       61,   43,   61,   61,   61,   61,   61,   61,   61,   61,
       49,   50,   51,   61,   61,   61,   61,   61,   42,   56,
        0,   61,   40,   61,   61,   61,   61,   61,   61,   61,
       61,   61,    0,    0,   61,   61,   61,   61,   61,   61,
        0,    0,   61,   61,   61,    0,    0,   61,    0,    0,
       61,    0,    0,    0,    0,    0,    0,    0,    0,   48,
       47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[380] =
    {   0,
        0,    0,   60,   61,   64,   65,   68,   69,  336, 1187,
     1187, 1187, 1187,  327, 1187,  296, 1187,   60, 1187,  281,
     1187, 1187, 1187,  255, 1187,   58,   64,   68,   68,   88,
     1187,   69,  243,   72,   84,   91, 1187, 1187, 1187,   96,
       93,   99,  105,  103,  113,  142,  115,  118,  135,  147,
      152,  154,  158,  175,  169,  160, 1187,  196, 1187, 1187,
     1187,  250, 1187, 1187,  243,  224,  207, 1187,  233, 1187,
      184, 1187, 1187,  177,    0, 1187, 1187, 1187,  200,  208,
      194, 1187, 1187,  220,  224,  235,  188,  244,  248,  240,
     1187, 1187, 1187, 1187, 1187,  228,  252,  256,  268,  259,

      264,  270,  274,  276,  278,  280,  284,  286,  289,  304,
      291,  297,  293,  306,  308,  314,  318,  320,  322,  210,
      330,  332,  335,  337,  340,  343,  345,  348,  352,  356,
      358,  366,  372,  378,  382,  384,  390,  392,  394,  398,
     1187, 1187, 1187, 1187,  188,  398, 1187, 1187,  182,  432,
      374,  411,  413,  162,  434,  436,  443,  454,  458,  462,
      403,  466,  470,  473,  484,  486,  478,  490,  493,  495,
      501,  504,  507,  512,  514,  516,  521,  525,  528,  530,
      532,  534,  537,  539,  544,  555,  559,  561,  563,  568,
      570,  572,  574,  576,  579,  590,  586,  595,  600,  602,

      604,  606,  613,  608,  617,  621,  628,  631,  634,  636,
      641,  643,  655,  658,  166,  663,  660,  665,  675,  680,
      685,  695,  687,  690,  697,  700,  705,  710,  712,  719,
      721,  723,  725,  727,  732,  734,  738,  743,  745,  749,
      751,  754,  759,  763,  767,  772,  775,  777,  780,  783,
      788,  792,  799,  797,  805,  807,  809,  811,  817,  819,
      823,  825,  830,  832,  836,  152,  840,  852,  855,  860,
      862,  864,  867,  870,  872,  834,  874,  880,  876,  889,
      884,  892,  896,  898,  900,  904,  911,  908,  913,  916,
      921,  927,  924,  934,  936,  938,  942,  945,  950,  947,

      952,  157,  961,  958,  954,  963,  976,  981,  983,  986,
      988,  990,  992,  994,  996,  999, 1002, 1004, 1006, 1008,
     1012, 1018, 1026, 1028, 1030, 1033, 1035, 1037, 1187, 1042,
      145, 1044, 1046, 1049, 1053, 1055, 1061, 1057, 1064, 1069,
     1071, 1079,  133,  122, 1082, 1084, 1086, 1088, 1091, 1095,
      136,  116, 1100, 1102, 1107,  109,  135, 1110,   94,   93,
     1116,  102,   86,  103,   85,   73,   70,   48,   45, 1187,
     1187, 1187, 1166, 1170, 1174,   90, 1178, 1182,   86
    } ;

static const flex_int16_t yy_def[380] =
    {   0,
      372,    1,  373,  373,  374,  374,  375,  375,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  376,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  376,  376,  372,  372,  372,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  377,  372,  372,  372,
      378,  372,  372,  376,  379,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  376,  376,  376,  379,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      372,  372,  372,  372,  377,  372,  372,  372,  377,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      376,  376,  376,  372,  379,  379,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  372,  372,  372,  372,  372,  372,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      372,  372,  372,  372,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  372,  376,
      372,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  372,  372,  376,  376,  376,  376,  376,  376,
      372,  372,  376,  376,  376,  372,  372,  376,  372,  372,
      376,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,    0,  372,  372,  372,  372,  372,  372,  372
    } ;

static const flex_int16_t yy_nxt[1250] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   18,   18,   35,   36,   37,
       10,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   18,   48,   18,   18,   49,   18,   50,   18,   51,
       52,   53,   54,   18,   55,   56,   18,   18,   18,   57,
       58,   59,   61,   61,   62,   62,   64,   64,   65,   65,
       68,   68,   69,   69,   77,   70,   70,   66,   66,   75,
       75,   82,   78,   79,   79,   84,   83,   85,   85,   75,
       80,   91,   92,   74,   86,   94,   95,  371,   71,   71,

      370,   87,   80,   75,   75,   84,   86,   88,   89,   81,
       75,   75,   75,   75,   86,   99,   99,  369,   75,   75,
      368,   90,   75,   75,   75,   75,   86,  367,  101,  100,
      366,   96,   75,   75,   75,   75,  365,   75,   75,  106,
      364,  110,  363,   97,  102,  362,  107,  103,   98,  104,
      108,  111,  360,  109,   75,   75,  105,  120,  112,  359,
      113,   75,   75,  119,  121,  122,   75,   75,  357,  114,
      356,   75,   75,   75,   75,  352,  115,   75,   75,   75,
       75,  124,  351,  123,  116,  125,  127,  117,   75,   75,
      118,  149,  130,  344,   75,   75,   75,   75,  329,  131,

      126,  140,  128,  138,  302,  129,  266,  159,  159,  215,
      132,  133,  146,  134,  149,  135,  136,  139,  146,  150,
      150,   87,  152,  149,  152,  137,   80,  153,  153,   75,
       75,  149,  154,  151,  149,  147,  149,  146,   80,  155,
      155,   84,  144,   85,   85,  143,   80,   75,   75,  157,
       86,  157,  142,  156,  158,  158,  141,   87,   80,  160,
      160,   84,   86,   88,   88,   84,   93,   88,   89,   77,
       86,   75,   75,   90,   86,   75,   75,   90,   99,   99,
      161,   90,   86,   75,   75,  164,   86,  165,  165,   75,
       75,   76,  100,   75,   75,   75,   75,   75,   75,   75,

       75,  166,  162,   75,   75,   75,   75,  163,   75,   75,
       75,   75,   75,   75,  170,  167,   75,   75,  174,   73,
      175,  168,  169,   75,   75,   75,   75,   75,   75,   72,
      171,  172,  173,   75,   75,  372,  176,   75,   75,   75,
       75,   75,   75,  177,  178,  372,  180,  372,  179,   75,
       75,   75,   75,  182,   75,   75,   75,   75,  181,   75,
       75,  183,   75,   75,   75,   75,  184,   75,   75,  372,
      185,   75,   75,  372,  186,   75,   75,   75,   75,  187,
      372,  193,  190,  188,  189,   75,   75,  196,  192,  191,
      194,   75,   75,  212,  212,  185,  195,   75,   75,  372,

      199,   75,   75,   75,   75,  145,  198,  151,  197,   75,
       75,   75,   75,   75,   75,  372,  200,   75,   75,  372,
      202,  201,   75,   75,  206,  152,  204,  152,  145,  203,
      153,  153,  213,  213,  205,  372,  209,  145,  372,  210,
      211,  223,  208,  207,  372,  145,  214,  185,  145,  372,
      145,  150,  150,  216,  216,  218,  218,  157,   80,  157,
       80,  372,  158,  158,  372,  151,  372,  217,  372,  156,
       80,  372,   80,  219,  219,   84,  372,  221,  221,   84,
      372,  222,  222,  372,   86,   75,   75,  220,   86,   75,
       75,   87,   79,   79,  372,   90,   86,   75,   75,   80,

       86,  164,  372,  165,  165,   99,   99,  372,  224,   75,
       75,   80,   75,   75,   75,   75,  372,  166,  372,  166,
       75,   75,  225,   75,   75,  372,   75,   75,  227,  229,
      226,   75,   75,   75,   75,   75,   75,  372,  228,  185,
       75,   75,  185,  230,   75,   75,  372,   75,   75,   75,
       75,   75,   75,   75,   75,  234,   75,   75,   75,   75,
      235,  372,  185,   75,   75,  231,  236,  232,  233,  372,
      237,  239,  372,  240,   75,   75,  185,  372,   75,   75,
       75,   75,   75,   75,  372,  238,  372,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,  372,   75,   75,

      372,  244,  372,  185,  241,   75,   75,  242,  185,   75,
       75,  372,  245,  243,   75,   75,  372,  185,  246,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,  372,
      247,  248,   75,   75,  372,  249,   75,   75,  372,  250,
       75,   75,  254,  372,  253,  251,  372,   75,   75,  256,
       75,   75,  252,   75,   75,   75,   75,  372,  255,  185,
       75,   75,  264,  264,  372,  257,  259,  372,  258,   80,
      262,  261,  372,  260,  213,  213,  151,  265,  265,  267,
      267,   80,  216,  216,  268,  268,  263,  372,  214,   80,
      372,  214,  372,  217,  219,  219,  217,  372,  156,  269,

      269,   80,   84,  372,  221,  221,   75,   75,  220,   75,
       75,   86,   84,  220,  222,  222,   75,   75,   87,   75,
       75,   86,  372,   86,   75,   75,  372,  270,   90,   75,
       75,   75,   75,   86,  372,  272,  372,  271,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,  275,  372,
      273,   75,   75,   75,   75,  274,  185,   75,   75,  372,
      185,  372,   75,   75,   75,   75,  372,  277,   75,   75,
       75,   75,  276,   75,   75,  185,  372,  279,   75,   75,
      278,  259,   75,   75,  372,  280,   75,   75,  372,  282,
      281,   75,   75,  284,   75,   75,   75,   75,  372,   75,

       75,  185,   75,   75,  283,  372,  287,   75,   75,  288,
      372,   75,   75,  285,  372,  289,   75,   75,   75,   75,
      372,  286,  290,  372,   75,   75,   75,   75,   75,   75,
       75,   75,  372,  291,  292,  293,   75,   75,   75,   75,
      185,  294,   75,   75,   75,   75,  372,  185,  295,   75,
       75,  264,  264,   75,   75,  301,  301,  372,   80,  303,
      303,  372,  297,  372,  296,  151,   80,  298,  300,  214,
       80,  268,  268,  217,  304,  304,  372,  299,   80,   75,
       75,   75,   75,   75,   75,  156,   75,   75,  220,   75,
       75,   75,   75,   75,   75,   75,   75,  372,  305,   75,

       75,  308,  306,   75,   75,  372,  309,  372,   75,   75,
      307,   75,   75,  372,  312,   75,   75,   75,   75,   75,
       75,  310,  185,   75,   75,  311,  313,   75,   75,  314,
       75,   75,   75,   75,  372,   75,   75,  372,  315,  317,
       75,   75,  185,   75,   75,  316,   75,   75,  185,  320,
      372,  318,  321,   75,   75,   75,   75,   75,   75,  372,
      319,   75,   75,  323,   75,   75,   75,   75,  322,   75,
       75,  301,  301,   75,   75,  185,  324,  304,  304,  372,
      303,  303,   75,   75,  326,  214,  325,   80,  372,  185,
      372,  220,  328,  331,  217,   75,   75,  372,  327,   80,

       75,   75,   75,   75,  330,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,  332,   75,   75,
      372,   75,   75,   75,   75,   75,   75,   75,   75,  372,
      333,   75,   75,  372,  335,  336,  337,   75,   75,  334,
      185,  372,  185,  185,  185,   75,   75,   75,   75,   75,
       75,  185,   75,   75,   75,   75,   75,   75,  372,  343,
      338,   75,   75,   75,   75,   75,   75,  339,   75,   75,
      372,  341,   75,   75,   75,   75,   75,   75,  340,  372,
       75,   75,  342,   75,   75,  372,  185,  185,   75,   75,
       75,   75,  372,  346,  372,  348,  185,  347,   75,   75,

      345,   75,   75,   75,   75,   75,   75,   75,   75,  372,
       75,   75,  372,  185,   75,   75,  349,  185,  350,   75,
       75,   75,   75,  372,  185,  185,   75,   75,  372,   75,
       75,  372,  354,  355,  353,   75,   75,  372,  372,  372,
      372,  185,  372,  372,  372,  372,  372,  185,  361,  372,
      372,  185,  372,  185,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  358,   60,   60,   60,   60,
       63,   63,   63,   63,   67,   67,   67,   67,  145,  372,
      372,  145,  148,  372,  148,  148,    9,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static const flex_int16_t yy_chk[1250] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    5,    6,
        7,    8,    7,    8,   26,    7,    8,    5,    6,   18,
       18,   28,   26,   27,   27,   29,   28,   29,   29,  379,
       27,   32,   32,  376,   29,   34,   34,  369,    7,    8,

      368,   29,   27,   35,   35,   30,   29,   30,   30,   27,
       36,   36,   41,   41,   30,   40,   40,  367,   42,   42,
      366,   30,   44,   44,   43,   43,   30,  365,   41,   40,
      364,   35,   45,   45,   47,   47,  363,   48,   48,   43,
      362,   44,  360,   36,   41,  359,   43,   42,   36,   42,
       43,   44,  357,   43,   49,   49,   42,   48,   45,  356,
       45,   46,   46,   47,   48,   48,   50,   50,  352,   45,
      351,   51,   51,   52,   52,  344,   46,   53,   53,   56,
       56,   50,  343,   49,   46,   50,   51,   46,   55,   55,
       46,   71,   52,  331,   54,   54,   74,   74,  302,   53,

       50,   56,   51,   55,  266,   51,  215,   87,   87,  154,
       53,   53,  149,   53,   71,   53,   54,   55,  145,   79,
       79,   87,   80,   71,   80,   54,   79,   80,   80,  120,
      120,   71,   81,   79,   71,   69,   71,   67,   79,   84,
       84,   85,   66,   85,   85,   65,   84,   96,   96,   86,
       85,   86,   62,   84,   86,   86,   58,   85,   84,   90,
       90,   88,   85,   88,   88,   89,   33,   89,   89,   24,
       88,   97,   97,   90,   89,   98,   98,   88,  100,  100,
       96,   89,   88,  101,  101,   99,   89,   99,   99,  102,
      102,   20,  100,  103,  103,  104,  104,  105,  105,  106,

      106,   99,   97,  107,  107,  108,  108,   98,  109,  109,
      111,  111,  113,  113,  104,  101,  112,  112,  107,   16,
      108,  102,  103,  110,  110,  114,  114,  115,  115,   14,
      105,  106,  106,  116,  116,    9,  109,  117,  117,  118,
      118,  119,  119,  110,  111,    0,  113,    0,  112,  121,
      121,  122,  122,  115,  123,  123,  124,  124,  114,  125,
      125,  116,  126,  126,  127,  127,  117,  128,  128,    0,
      118,  129,  129,    0,  119,  130,  130,  131,  131,  121,
        0,  127,  123,  122,  122,  132,  132,  129,  126,  124,
      128,  133,  133,  151,  151,  125,  128,  134,  134,    0,

      132,  135,  135,  136,  136,  146,  131,  151,  130,  137,
      137,  138,  138,  139,  139,    0,  132,  140,  140,    0,
      134,  133,  161,  161,  137,  152,  136,  152,  146,  135,
      152,  152,  153,  153,  136,    0,  139,  146,    0,  139,
      140,  161,  138,  137,    0,  146,  153,  137,  146,    0,
      146,  150,  150,  155,  155,  156,  156,  157,  150,  157,
      155,    0,  157,  157,    0,  150,    0,  155,    0,  156,
      150,    0,  155,  158,  158,  159,    0,  159,  159,  160,
        0,  160,  160,    0,  159,  162,  162,  158,  160,  163,
      163,  159,  164,  164,    0,  160,  159,  167,  167,  164,

      160,  165,    0,  165,  165,  166,  166,    0,  162,  168,
      168,  164,  169,  169,  170,  170,    0,  165,    0,  166,
      171,  171,  163,  172,  172,    0,  173,  173,  168,  170,
      167,  174,  174,  175,  175,  176,  176,    0,  169,  171,
      177,  177,  172,  173,  178,  178,    0,  179,  179,  180,
      180,  181,  181,  182,  182,  177,  183,  183,  184,  184,
      178,    0,  174,  185,  185,  175,  179,  176,  176,    0,
      181,  183,    0,  184,  186,  186,  180,    0,  187,  187,
      188,  188,  189,  189,    0,  182,    0,  190,  190,  191,
      191,  192,  192,  193,  193,  194,  194,    0,  195,  195,

        0,  189,    0,  186,  187,  197,  197,  187,  190,  196,
      196,    0,  191,  188,  198,  198,    0,  192,  193,  199,
      199,  200,  200,  201,  201,  202,  202,  204,  204,    0,
      194,  195,  203,  203,    0,  196,  205,  205,    0,  197,
      206,  206,  201,    0,  200,  198,    0,  207,  207,  203,
      208,  208,  199,  209,  209,  210,  210,    0,  202,  204,
      211,  211,  212,  212,    0,  205,  207,    0,  206,  212,
      210,  209,    0,  208,  213,  213,  212,  214,  214,  217,
      217,  212,  216,  216,  218,  218,  211,    0,  213,  216,
        0,  214,    0,  217,  219,  219,  216,    0,  218,  220,

      220,  216,  221,    0,  221,  221,  223,  223,  219,  224,
      224,  221,  222,  220,  222,  222,  225,  225,  221,  226,
      226,  222,    0,  221,  227,  227,    0,  223,  222,  228,
      228,  229,  229,  222,    0,  225,    0,  224,  230,  230,
      231,  231,  232,  232,  233,  233,  234,  234,  228,    0,
      226,  235,  235,  236,  236,  227,  229,  237,  237,    0,
      230,    0,  238,  238,  239,  239,    0,  233,  240,  240,
      241,  241,  231,  242,  242,  232,    0,  235,  243,  243,
      234,  238,  244,  244,    0,  237,  245,  245,    0,  241,
      239,  246,  246,  243,  247,  247,  248,  248,    0,  249,

      249,  240,  250,  250,  242,    0,  246,  251,  251,  247,
        0,  252,  252,  244,    0,  248,  254,  254,  253,  253,
        0,  245,  249,    0,  255,  255,  256,  256,  257,  257,
      258,  258,    0,  250,  252,  253,  259,  259,  260,  260,
      251,  255,  261,  261,  262,  262,    0,  254,  256,  263,
      263,  264,  264,  276,  276,  265,  265,    0,  264,  267,
      267,    0,  258,    0,  257,  264,  267,  260,  263,  265,
      264,  268,  268,  267,  269,  269,    0,  262,  267,  270,
      270,  271,  271,  272,  272,  268,  273,  273,  269,  274,
      274,  275,  275,  277,  277,  279,  279,    0,  270,  278,

      278,  273,  271,  281,  281,    0,  275,    0,  280,  280,
      272,  282,  282,    0,  279,  283,  283,  284,  284,  285,
      285,  277,  274,  286,  286,  278,  280,  288,  288,  281,
      287,  287,  289,  289,    0,  290,  290,    0,  282,  285,
      291,  291,  286,  293,  293,  284,  292,  292,  283,  289,
        0,  287,  290,  294,  294,  295,  295,  296,  296,    0,
      288,  297,  297,  292,  298,  298,  300,  300,  291,  299,
      299,  301,  301,  305,  305,  294,  293,  304,  304,    0,
      303,  303,  306,  306,  297,  301,  295,  303,    0,  296,
        0,  304,  299,  307,  303,  307,  307,    0,  298,  303,

      308,  308,  309,  309,  305,  310,  310,  311,  311,  312,
      312,  313,  313,  314,  314,  315,  315,  308,  316,  316,
        0,  317,  317,  318,  318,  319,  319,  320,  320,    0,
      309,  321,  321,    0,  315,  316,  317,  322,  322,  310,
      311,    0,  318,  313,  319,  323,  323,  324,  324,  325,
      325,  314,  326,  326,  327,  327,  328,  328,    0,  330,
      320,  330,  330,  332,  332,  333,  333,  324,  334,  334,
        0,  326,  335,  335,  336,  336,  338,  338,  325,    0,
      337,  337,  328,  339,  339,    0,  327,  334,  340,  340,
      341,  341,    0,  336,    0,  338,  332,  337,  342,  342,

      335,  345,  345,  346,  346,  347,  347,  348,  348,    0,
      349,  349,    0,  339,  350,  350,  340,  342,  341,  353,
      353,  354,  354,    0,  347,  348,  355,  355,    0,  358,
      358,    0,  346,  349,  345,  361,  361,    0,    0,    0,
        0,  354,    0,    0,    0,    0,    0,  350,  358,    0,
        0,  353,    0,  361,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  355,  373,  373,  373,  373,
      374,  374,  374,  374,  375,  375,  375,  375,  377,    0,
        0,  377,  378,    0,  378,  378,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
/*
Miguel Filipe de Andrade Sergio 2020225643
Filipe David Amado Mendes 2020218797
*/
#line 844 "lex.yy.c"
#line 19 "jucompiler.l"
    #include <stdbool.h>
    #include "functions.h"
	#include "y.tab.h"

    int line = 1, column = 1;
    int column_aux = 1, line_aux = 1;
    char buffer[256];
    int buffer_flag = 0; 
	int flag = 0;
	extern int flag_error;

	int yyparse(void);
#line 858 "lex.yy.c"

#line 860 "lex.yy.c"

#define INITIAL 0
#define SINGLECOMM 1
#define MULTPLECOMM 2
#define SLIT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "jucompiler.l"


#line 1083 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 373 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1187 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{BEGIN SINGLECOMM; column+=yyleng;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 38 "jucompiler.l"
{line++; column = 1; BEGIN 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "jucompiler.l"
{line_aux =  line; column_aux = column; column += yyleng; BEGIN MULTPLECOMM;}  
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{column += yyleng; BEGIN 0;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 43 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case YY_STATE_EOF(MULTPLECOMM):
#line 45 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", line_aux, column_aux);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{BEGIN SLIT; buffer[0]=0; strcat(buffer, yytext); line_aux = line; column_aux = column; column+=yyleng; buffer_flag = 0;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{column+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{strcat(buffer, yytext);printf("Line %d, col %d: invalid escape sequence (%s)\n",line,column,yytext); column += yyleng; buffer_flag = 1;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 51 "jucompiler.l"
{BEGIN 0; buffer[0] = 0; printf("Line %d, col %d: unterminated string literal\n",line_aux,column_aux); line++; column = 1;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{BEGIN 0; strcat(buffer, yytext); if(flag == 1 && buffer_flag==0)printf("STRLIT(%s)\n",buffer);column+=yyleng;
										if(flag != 1 && buffer_flag == 0) {
											yylval.id = strdup(buffer);
											yytext = buffer;
											return STRLIT;
										}
									}
	YY_BREAK
case YY_STATE_EOF(SLIT):
#line 59 "jucompiler.l"
{BEGIN 0; buffer[0] = 0; printf("Line %d, col %d: unterminated string literal\n",line_aux,column_aux); line++; column = 1;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if (flag == 1) printf("AND\n"); column += yyleng; if(flag != 1) return AND; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if (flag == 1) printf("ASSIGN\n"); column += yyleng; if(flag != 1) return ASSIGN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if (flag == 1) printf("STAR\n"); column += yyleng; if(flag != 1) return STAR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if (flag == 1) printf("COMMA\n"); column += yyleng; if(flag != 1) return COMMA; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if (flag == 1) printf("DIV\n"); column += yyleng; if(flag != 1) return DIV; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if (flag == 1) printf("EQ\n"); column += yyleng; if(flag != 1) return EQ; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if (flag == 1) printf("GE\n"); column += yyleng; if(flag != 1) return GE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if (flag == 1) printf("GT\n"); column += yyleng; if(flag != 1) return GT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if (flag == 1) printf("LBRACE\n"); column += yyleng; if(flag != 1) return LBRACE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if (flag == 1) printf("LE\n"); column += yyleng; if(flag != 1) return LE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if (flag == 1) printf("LPAR\n"); column += yyleng; if(flag != 1) return LPAR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if (flag == 1) printf("LSQ\n"); column += yyleng; if(flag != 1) return LSQ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if (flag == 1) printf("LT\n"); column += yyleng; if(flag != 1) return LT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if (flag == 1) printf("MINUS\n"); column += yyleng; if(flag != 1) return MINUS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if (flag == 1) printf("MOD\n"); column += yyleng; if(flag != 1) return MOD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if (flag == 1) printf("NE\n"); column += yyleng; if(flag != 1) return NE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if (flag == 1) printf("NOT\n"); column += yyleng; if(flag != 1) return NOT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if (flag == 1) printf("OR\n"); column += yyleng; if(flag != 1) return OR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if (flag == 1) printf("PLUS\n"); column += yyleng; if(flag != 1) return PLUS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if (flag == 1) printf("RBRACE\n"); column += yyleng; if(flag != 1) return RBRACE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if (flag == 1) printf("RPAR\n"); column += yyleng; if(flag != 1) return RPAR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if (flag == 1) printf("RSQ\n"); column += yyleng; if(flag != 1) return RSQ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if (flag == 1) printf("SEMICOLON\n"); column += yyleng; if(flag != 1) return SEMICOLON; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if (flag == 1) printf("ARROW\n"); column += yyleng; if(flag != 1) return ARROW; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if (flag == 1) printf("LSHIFT\n"); column += yyleng; if(flag != 1) return LSHIFT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if (flag == 1) printf("RSHIFT\n"); column += yyleng; if(flag != 1) return RSHIFT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if (flag == 1) printf("XOR\n"); column += yyleng; if(flag != 1) return XOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if (flag == 1) printf("BOOL\n"); column += yyleng; if(flag != 1) return BOOL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if (flag == 1) printf("CLASS\n"); column += yyleng; if(flag != 1) return CLASS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if (flag == 1) printf("DOTLENGTH\n"); column += yyleng; if(flag != 1) return DOTLENGTH; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if (flag == 1) printf("DOUBLE\n"); column += yyleng; if(flag != 1) return DOUBLE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if (flag == 1) printf("ELSE\n"); column += yyleng; if(flag != 1) return ELSE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if (flag == 1) printf("IF\n"); column += yyleng; if(flag != 1) return IF; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if (flag == 1) printf("INT\n"); column += yyleng; if(flag != 1) return INT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if (flag == 1) printf("PRINT\n"); column += yyleng; if(flag != 1) return PRINT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if (flag == 1) printf("PARSEINT\n"); column += yyleng; if(flag != 1) return PARSEINT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if (flag == 1) printf("PUBLIC\n"); column += yyleng; if(flag != 1) return PUBLIC; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if (flag == 1) printf("RETURN\n"); column += yyleng; if(flag != 1) return RETURN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if (flag == 1) printf("STATIC\n"); column += yyleng; if(flag != 1) return STATIC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if (flag == 1) printf("STRING\n"); column += yyleng; if(flag != 1) return STRING; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if (flag == 1) printf("VOID\n"); column += yyleng; if(flag != 1) return VOID; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if (flag == 1) printf("WHILE\n"); column += yyleng; if(flag != 1) return WHILE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if(flag == 1)printf("BOOLLIT(%s)\n",yytext);column+=yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return BOOLLIT;
									    }
                                    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if(flag == 1)printf("RESERVED(%s)\n",yytext);column+=yyleng; if(flag != 1)return RESERVED;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{column+=yyleng;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{column+=yyleng;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{column += yyleng; }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 116 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if(flag == 1)printf("ID(%s)\n",yytext);column+=yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return ID;
										}
          							}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "jucompiler.l"
{if (flag == 1) printf("INTLIT(%s)\n", yytext); column += yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return INTLIT;
										} 
									}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "jucompiler.l"
{if (flag == 1) printf("REALLIT(%s)\n", yytext); column += yyleng;
										if(flag != 1) {
											yylval.id = strdup(yytext);
											return REALLIT;
										}
									}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 136 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", line, column, yytext); column += yyleng; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 138 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1503 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLECOMM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 373 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 373 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 372);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 138 "jucompiler.l"



int yywrap() {
	return 1;
}

void yyerror(const char *s) { 
     printf ("Line %d, col %d: %s: %s\n", line, (int)(column-strlen(yytext)), s, yytext);
}


int main(int argc, char *argv[]) {
	if (argc > 1) {
		if (strcmp(argv[1],"-l") == 0) {
			flag = 1;
			yyparse();
		}
		else if (strcmp(argv[1],"-t") == 0) {
			// análise lexical, análise sintatica e PRINT TREE
			flag = 2;
			yyparse();
		}
		else if (strcmp(argv[1], "-e1") == 0) {
			flag = 0;
			while (yylex() != 0) {
				;
			}
		}
		else if (strcmp(argv[1], "-e2") == 0) {
			flag = 0;
			flag_error = 1;
			yyparse();
			yylex();
		}
	}
}
